### ISSUE TITLE
Wrong cases 8,13,15

### ISSUE THREAD

**Issue by rafaelcarpeta** [Nuxar1/DecryptionDumper#1]
getting this error on those cases:
 rcx = imageBase;                //sub rcx, [rbp-0x70] -- didn't find trace -> use base
 
 on patch 1.50.2, using client info sig +0xA8 for client_base.
 same issue with client base pattern 48 8B 83 ?? ?? ?? ?? C6 44 24 ?? ?? 0F B6 4C 24 ?? 83

**Comment by Nuxar1** [comment]
It does so if the value stored in stack wasn't written to within the decryption but somewhere before. This usually means it's the process base but you should check it manually with IDA.

**Comment by rafaelcarpeta** [comment]
ok so, on ida imageBase is loaded on r9, them its moved to rbp - 0x70.
`.text:00007FF7D183B96C                 lea     r9, cs:7FF7CF060000h`
`.text:00007FF7D183B973                 xor     eax, 3`
`.text:00007FF7D183B976                 mov     [rbp-70h], r9`

so "sub rcx, [rbp-0x70]" it should translate to:
`rcx -= *(uint64_t*)(imageBase - 0x70);`
 is that correct?

**Comment by Nuxar1** [comment]
That is correct. I thought I made it do the tight operation though. Are u using the latest version?

**Comment by rafaelcarpeta** [comment]
Yes I'm on last version

**Comment by Nuxar1** [comment]
I will work on a fix today.

**Comment by Nuxar1** [comment]
I'm quiet sure you didn't use the latest version as there was a fix for this. I have pushed another commit that fixed the same issue for RSP (not only RBP) as for some reason i forgot to change it there too.
https://github.com/Nuxar1/DecryptionDumper/commit/3bdc36196354d4cf3b3b6755d8e4a203b8c4a85f
