### ISSUE TITLE
General Questions 

### ISSUE THREAD

**Issue by drdisconnect872** [Nuxar1/DecryptionDumper#3]
Hey @Nuxar1 thanks for sharing the tool. I have one question. Do we need to update the decryption? Inorder to get the offsets? As far as I know we need to update the decryption when there is an update to the game

**Comment by drdisconnet** [comment]
Also, some of the values are red in the console. How do I update that? Do I have to change the pattern?

**Comment by Nuxar1** [comment]
If an offset is printed red and the value is 0 it means the pattern didn't return any results or the result was at an unexpected location (it does some basic checks on the instruction).

If something within the decryption routine is printed red, you should look at the text and double check in IDA at that instruction if needed.
If it fails to decode an instruction it will always print the assembly code so you can manually translate it to c code.

It might also print failed to find [...]. In that case you'll need to update the pattern it uses to find [...].

Your last solution would be to alter the code.
