### ISSUE TITLE
Failed to attach to process. Error code: 0X5

### ISSUE THREAD

**Issue by ccxt0001** [Nuxar1/DecryptionDumper#8]
hi @Nuxar1 May I ask how to fix this error?

Failed to attach to process. Error code: 0X5

**Comment by Nuxar1** [comment]
Look up system error codes for windows.

**Comment by ccxt0001** [comment]
thk @Nuxar1 
my mistake sorry.
i spent a minute searching google.


HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System
EnableLUA = 0

problem solved.
